### ISSUE TITLE
Docs are ready for open sourcing

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#272]
## TODO:
- [x] All Transforms are completely documented.
- [x] transform chain requirements are documented.
- [x] Create toc for transforms page
- [x] Remove implementation details e.g. concepts.md page is realllly bad at this.
- [x] Complete all TODOs in the docs

**Comment by conorbros** [comment]
Did we finish all of this?

**Comment by rukai** [comment]
nope:
* plenty of TODOs in the docs to address
* need to check over the transforms
* need to check for implementation details

**Comment by rukai** [comment]
There are still transforms with poor docs, but open sourcing has already been completed.
I think we should close this and improve the docs of those transforms when we actually work on making those transforms production worthy.
