### ISSUE TITLE
Cassandra sink single todo

### ISSUE THREAD

**Issue by conorbros** [shotover/shotover-proxy#391]
- [x] #93 
- [x] #522
- [x] Authentication & integration tests for auth
- [x] #208 
- [ ] #160 
- [x] #94 
- [x] #500
- [x] #392 
- [x] investigate using the node implementation from cdrs-tokio instead of the current one
- [x] https://github.com/shotover/shotover-proxy/issues/459
- [x] benchmarks

**Comment by rukai** [comment]
we can just let https://github.com/shotover/shotover-proxy/issues/160 track the v5 support
