### ISSUE TITLE
Redesign MessageDetails

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#445]
## TODO
Break down of PRs that need to be made to complete the rewrite.
The stage headings demonstrate dependencies between PR's, e.g. Stage 3 PRs are dependent on Stage 2 PRs
Many of these items already have a corresponding implementation in https://github.com/shotover/shotover-proxy/pull/453 so please refer there first. The item will say `(take from PR)` if the functionality is already implemented in the draft PR.

### Stage 1
- [x] #454
- [x] #462
- [x] #495
- [x] #505

### Stage 2
- [x] #476
- [x] #472
- [x] #473
- [x] #474
- [x] #475
- [ ] Implement MessageInner. Frame, CassandraFrame and new Message constructors. Dont use them yet though (take from PR) (Can be further split up if you want)

### Stage 3
- [ ] Draw the rest of the owl. We might be able to further split up by trying to have some transforms run on the old system and some on the new. But I think it would be better at this point to just swap everything over. (refer to the PR)

### Stage 4
- [ ] Remove message decoding flags from source config (pull from PR)

## Problems

The handling of MessageDetails is a bit of a mess currently:
* Modifying just the raw message or message details leaves the other out of sync. We should pick one to be the source of truth and then generate the other from it.
* Some transforms expect the message details to be already generated, others will trigger generation of message details when they need it. We should handle this in a uniform way.
* There is duplicated yaml configuration across the Cassandra source and RedisCache for determining the pks to store in the message details, we should improve configuration by having the transform specify the pks it needs provided in the message details.

## Current instances of modifying messages

* RedisClusterPortsRewrite - modifies RawFrame (of the response)
* RedisTimestampTagger - modifies MessageDetails::Query(QueryMessage { ast, .. }) and MessageDetails::Response(QueryResponse { response_meta, result, .. })
* RedisCache - doesnt do anything yet but will soon - prompted me to investigate this issue.

## Proposed Redesign

Generate each part of QueryMessage/QueryResponse on demand in the transforms.
The only way to modify the message is by modifying the RawFrame which is extended to include the CSQL ast.

Effects:
* Make transforms drastically more robust, one source of truth means transforms are always reading the message provided by the previous transform.
* By requesting each part individually it should improve performance over generating MessageDetails up front for every message
    + Only a subset of messages in a subset of transforms need access to a subset of MessageDetails
* Performance would also degrade due to regenerating the same data across different transforms, to solve this we could add caching for it with automatic invalidation, but lets leave that until we can measure performance benefits of adding it.
    + we would include an automatic invalidation system on Message where requesting mutable access to the RawFrame clears the details cache.
* Alternatively instead of caching details we might see better performance by making use of the temporariness to write allocationless parsers.
* The transform has more control over the way message details are processed, preventing the need for duplicate configuration across source and transforms. (solves the Cassandra source / RedisCache problem I described earlier)
* The user doesnt need to manually turn query processing on/off for performance reasons, shotover just does the appropriate thing by default

### A bit more concretely

```rust
#[derive(PartialEq, Debug, Clone)]
pub struct Message {
    // TODO: caching fields could go here
    inner: Option<MessageInner>,
}

impl Message {
    pub fn from_bytes(bytes: Bytes, message_type: MessageType) -> Self {
        Message {
            inner: Some(MessageInner::RawBytes {
                bytes,
                message_type,
            }),
        }
    }

    pub fn from_bytes_and_frame(bytes: Bytes, frame: Frame) -> Self {
        Message {
            inner: Some(MessageInner::Parsed { bytes, frame }),
        }
    }

    pub fn from_frame(frame: Frame) -> Self {
        Message {
            inner: Some(MessageInner::Modified { frame }),
        }
    }

    pub fn get_frame(&mut self) -> &mut Frame {
        self.inner = self.inner.take().map(|x| x.into_parsed());

        match self.inner.as_mut().unwrap() {
            MessageInner::RawBytes { .. } => unreachable!(),
            MessageInner::Parsed { frame, .. } => frame,
            MessageInner::Modified { frame } => frame,
        }
    }

    pub fn invalidate_cache(&mut self) {
        // TODO: clear message details cache fields if we ever add any

        self.inner = self.inner.take().map(|x| x.into_modified());
    }

    pub fn get_query_type(&mut self) -> QueryType {
        match self.frame() {
            Frame::Cassandra(cassandra) => cassandra.get_query_type(),
            Frame::Redis(redis) => crate::protocols::redis_codec::redis_query_type(redis), // free-standing function as we cant define methods on RedisFrame
            Frame::None => QueryType::ReadWrite,
        }
    }
    // TODO: ... and other generic getter functions
}

/// There are 3 levels of processing the message can be in.
/// RawBytes -> Parsed -> Modified
/// Where possible transforms should avoid moving to further stages to improve performance but this is an implementation detail hidden from them
#[derive(PartialEq, Debug, Clone)]
enum MessageInner {
    RawBytes {
        bytes: Bytes,
        message_type: MessageType,
    },
    Parsed {
        bytes: Bytes,
        frame: Frame,
    },
    Modified {
        frame: Frame,
    },
}

impl MessageInner {
    fn into_parsed(self) -> Self {
        match self {
            MessageInner::RawBytes {
                bytes,
                message_type: _message_type,
            } => MessageInner::Parsed {
                bytes,
                frame: todo!(),
            },
            MessageInner::Parsed { .. } => self,
            MessageInner::Modified { .. } => self,
        }
    }
    fn into_modified(self) -> Self {
        match self {
            MessageInner::RawBytes { .. } => unimplemented!(),
            MessageInner::Parsed { frame, .. } => MessageInner::Modified { frame },
            MessageInner::Modified { .. } => self,
        }
    }
}

#[derive(PartialEq, Debug, Clone)]
pub enum MessageType {
    Redis,
    Cassandra,
}

#[derive(PartialEq, Debug, Clone)]
pub enum Frame {
    Cassandra(cassandra::CassandraFrame),
    Redis(redis_protocol::resp2::prelude::Frame),
    None,
}

#[derive(PartialEq, Debug, Clone)]
pub struct CassandraFrame {
    pub version: Version,
    pub stream_id: StreamId,
    pub tracing_id: Option<Uuid>,
    pub warnings: Vec<String>,
    /// Contains the message body
    pub operation: CassandraOperation,
}

impl CassandraFrame {
    pub fn get_query_type(&mut self) -> QueryType {
        todo!()
    }
}

#[derive(PartialEq, Debug, Clone)]
pub enum CassandraOperation {
    Query(Box<Statement>),
    Result(Value),
    Error(ErrorBody),
    /// One of many operations that performs protocol negotiation and should be ignored by transforms
    Protocol,
}
```

## What next

I will come up with a prototype to demonstrate this but in the mean time would love to hear the teams thoughts about this.

**Comment by benbromhead** [comment]
I largely agree that MessageDetails needs a bit of a rethink as the ergonomics are confusing at best. 

**Original Intent + History**
MessageDetails was never intended to provide a semantic translation layer between databases, but rather an "enriched view" of the message frame. Transforms that care about the query as represented by the MessageDetails already have to be "colored" to the ASTHolder enum which seperates out the "enriched view" based on the query language (e.g CQL, RESP etc). 

MessageDetails also contains a few other parts that generally appear to be universal to most databases. For example namespaces (e.g. schemas, keyspaces, table names, document collections etc), primary keys (if applicable to the query, all databases need a manner to uniquely address content) and results (for query responses).  

As we add more database protocols, we are likely to encounter situations where the database protocol is seperate, but the query language might be common (e.g. the various SQLs... to some degree). This was why the AST generated from a query is seperate from the Frame. 

It then followed that it might be friendlier to modify the ASTs / parsed queries and then generate a frame from them, rather than having to modify the frame directly. Transform authors should be able to spend most of their time thinking at the query level. This brought about the flag `modified` which mean that the codec would have to rebuild the frame based off the AST if it was set to true. The original Frame was then overwritten before the codec put it on the wire. 

Some of this thinking is why we don't have a great seperation of responsibilities in the codebase as too many parts, at different levels need to know about ASTs! I actually at one point tried to seperate some of this stuff into individual modules (with the idea you could just have a single module for a single transform), however the above ment that circular dependencies were problematic. At that point, i figured that would be a job for later :) I guess later is now!

As for the performance side of things. We actually hit perf issues with MessageDetails pretty quickly in our first set of testing with pubnub. The generation of MessageDetails should now only happen once thanks to `generate_message_details_query()` on the message struct. This function arose from perf issues while building out Redis multi-region stuff and so has largely been unevenly applied (hence why some transforms just expect it, when they should call the above function).

**Path forward**
I don't want to be too prescriptive about redesigning MessageDetails, however I do have some strong opinions about what it should be like to write a Transform and use an "enriched view" of a given query/response frame. I think you have covered some of this above in your proposal as well which is great!

- Transform authors should be able to largely think about the problem they are solving at the query level. What I mean by this, is that modifying a database query should require the least amount of yak shaving / scaffolding possible. E.g. `message.get_sql_ast()` and off you go.
- Transform authors should just be able to focus on the language / ast / protocol they care about. E.g. if the message is a redis query, they just start with `if let DatabaseEnum::Redis(redis_ast) = message { .. }` (or something similar) without it breaking! (this point sounds like the above, but one is about ease of access, the other is about safety of not trying to parse something unexpected).
- Speed - I don't know if its faster to reparse frames / query strings or to parse once but store the result (this makes the size of the message on the stack a lot bigger obvs), but stuff should be fast :)
- Consistent - Irrespective of what the upstream or downstream transform does, the author of the current Transform should not have to write code any differently.

If we are able to satisfy the above + but also simplify codec and source implementations that would be great, but Transform developer ergonomics should be the main priority (after taking security and correctness into account)!

**Comment by rukai** [comment]
Oh I totally missed that ASTHolder was split into a SQL style and a redis style ast.
I'll update to my design to take that into account.

**Comment by Claudenw** [comment]
Suppose we take the AST as the source of truth, then at a minimum a transform would have to send the correct AST down the pipe.  If we consider everything else as nice to have, then the transform would ensure that anything that is no accurate with respect to the AST is not send down the pipe.

So when a transform begins the AST is there and correct, any other information that is there is correct and doesn't need to be regenerated.  Anything missing the transform takes the hit on regeneration.

That said, the AST for Cassandra gets a bit weird.

The Jena project simply parses the query into an internal representation and then uses only the internal representation until it has to be serialized out of the system into text (human readable output) or storage.

**Comment by Claude-at-Instaclustr** [comment]
There are a number of Cassandra queries that can not be parsed currently:

- INSERT INTO test_type_keyspace.test_table (id, foo) VALUES (1, {foo: 'yes', bar: 1})
- CREATE KEYSPACE keyspace_tests_create WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
- USE system
- CREATE KEYSPACE keyspace_tests_delete_me WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
- DROP KEYSPACE keyspace_tests_delete_me
- CREATE KEYSPACE keyspace_tests_alter_me WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 } AND DURABLE_WRITES = false;
- ALTER KEYSPACE keyspace_tests_alter_me WITH DURABLE_WRITES = true;
- CREATE TYPE test_type_keyspace.test_type_name (foo text, bar int)
- INSERT INTO test_type_keyspace.test_table (id, foo) VALUES (1, {foo: 'yes', bar: 1})
- DROP TYPE test_type_keyspace.test_type_drop_me;
- CREATE KEYSPACE test_function_keyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
- BEGIN BATCH
- APPLY BATCH;
- CREATE FUNCTION test_function_keyspace.my_function (a int, b int) RETURNS NULL ON NULL INPUT RETURNS int LANGUAGE javascript AS 'a * b';
- DROP FUNCTION test_function_keyspace.my_function

**Comment by Claude-at-Instaclustr** [comment]
After taking a longer look at this issue and the bits that Cassandra has I no longer think the AST should be the source of truth, primarily because we don't have a good parser for CQL and it does not appear that it will be easy to build one.  On the other hand we do have the Frame.  We know the Frame is valid because that is what was parsed from the original information on the wire. 

I think the Frame should be the source of truth and code that modifies the frame in ways that invalidate the components of the MessageDetails should remove or repopulate those components.  

I think we should therefore work at creating Frame wrappers that can quickly read/write the native frame.  Perhaps define a trait that all frame wrappers implement to make some of the logic common across the different implementations, but still leave room for frame specific stuff.

**Comment by benbromhead** [comment]
> I think we should therefore work at creating Frame wrappers that can quickly read/write the native frame. Perhaps define a trait that all frame wrappers implement to make some of the logic common across the different implementations, but still leave room for frame specific stuff.

Parsing the query from the frame using a zero-copy approach into an AST that is a "view" over the frame sounds like the best way to do this?

**Comment by rukai** [comment]
Finished! :tada:
